version: "3.8"

services:
  aikdownloader:
    build: .
    image: dstansice/aikdownloader:latest
    container_name: aikdownloader
    ports:
      - "3666:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
